//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aiala.mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aiala.mobile.Resources.ServerMessages", typeof(ServerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the user profile..
        /// </summary>
        public static string Directory_LoadUserInfoError {
            get {
                return ResourceManager.GetString("Directory_LoadUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while ending an emergency..
        /// </summary>
        public static string EmergencyActivity_EndError {
            get {
                return ResourceManager.GetString("EmergencyActivity_EndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting an emergency..
        /// </summary>
        public static string EmergencyActivity_StartError {
            get {
                return ResourceManager.GetString("EmergencyActivity_StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating an emergency..
        /// </summary>
        public static string EmergencyActivity_UpdateError {
            get {
                return ResourceManager.GetString("EmergencyActivity_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error whhile loading gallery items..
        /// </summary>
        public static string Gallery_LoadError {
            get {
                return ResourceManager.GetString("Gallery_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading a picture to gallery..
        /// </summary>
        public static string Gallery_UploadPictureError {
            get {
                return ResourceManager.GetString("Gallery_UploadPictureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while logging an activity..
        /// </summary>
        public static string GenericActivity_Error {
            get {
                return ResourceManager.GetString("GenericActivity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the schedule..
        /// </summary>
        public static string Schedule_LoadError {
            get {
                return ResourceManager.GetString("Schedule_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating a step..
        /// </summary>
        public static string StepActivity_Error {
            get {
                return ResourceManager.GetString("StepActivity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating a task..
        /// </summary>
        public static string TaskActivity_Error {
            get {
                return ResourceManager.GetString("TaskActivity_Error", resourceCulture);
            }
        }
    }
}
