//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aiala.mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aiala.mobile.Resources.UiTexts", typeof(UiTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this picture?.
        /// </summary>
        public static string Communicate_DeleteQuestion {
            get {
                return ResourceManager.GetString("Communicate_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete picture.
        /// </summary>
        public static string Communicate_DeleteTitle {
            get {
                return ResourceManager.GetString("Communicate_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar pictures in your gallery.
        /// </summary>
        public static string Communicate_RelatedPictures {
            get {
                return ResourceManager.GetString("Communicate_RelatedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Communicate_Title {
            get {
                return ResourceManager.GetString("Communicate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Communicate_TitleDetail {
            get {
                return ResourceManager.GetString("Communicate_TitleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Emergency.
        /// </summary>
        public static string Emergency_EndEmergency {
            get {
                return ResourceManager.GetString("Emergency_EndEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Emergency_MoodBad {
            get {
                return ResourceManager.GetString("Emergency_MoodBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better.
        /// </summary>
        public static string Emergency_MoodBetter {
            get {
                return ResourceManager.GetString("Emergency_MoodBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improving.
        /// </summary>
        public static string Emergency_MoodImproving {
            get {
                return ResourceManager.GetString("Emergency_MoodImproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are you doing?.
        /// </summary>
        public static string Emergency_MoodQuestion {
            get {
                return ResourceManager.GetString("Emergency_MoodQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency_Title {
            get {
                return ResourceManager.GetString("Emergency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just completed the task!
        ///How do you feel?.
        /// </summary>
        public static string Feedback_HowDoYouFeel {
            get {
                return ResourceManager.GetString("Feedback_HowDoYouFeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks.
        /// </summary>
        public static string Home_AllTasks {
            get {
                return ResourceManager.GetString("Home_AllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any information available at the moment..
        /// </summary>
        public static string Home_NoData {
            get {
                return ResourceManager.GetString("Home_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See less.
        /// </summary>
        public static string Home_SeeLess {
            get {
                return ResourceManager.GetString("Home_SeeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in.
        /// </summary>
        public static string Login_AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("Login_AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login by entering your credentials..
        /// </summary>
        public static string Login_EnterCredentials {
            get {
                return ResourceManager.GetString("Login_EnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username or Password?.
        /// </summary>
        public static string Login_ForgotPasswordLink {
            get {
                return ResourceManager.GetString("Login_ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connectivity.
        /// </summary>
        public static string Login_NoNetwork {
            get {
                return ResourceManager.GetString("Login_NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to AIALA?.
        /// </summary>
        public static string Login_RegisterLink {
            get {
                return ResourceManager.GetString("Login_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AIALA.
        /// </summary>
        public static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Master_Logout {
            get {
                return ResourceManager.GetString("Master_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Master_Settings {
            get {
                return ResourceManager.GetString("Master_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task location.
        /// </summary>
        public static string Navigate_NoTaskLocation {
            get {
                return ResourceManager.GetString("Navigate_NoTaskLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Navigate_Title {
            get {
                return ResourceManager.GetString("Navigate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where am I?.
        /// </summary>
        public static string Navigate_WhereAmI {
            get {
                return ResourceManager.GetString("Navigate_WhereAmI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable developer mode.
        /// </summary>
        public static string Settings_DisableDevMode {
            get {
                return ResourceManager.GetString("Settings_DisableDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer mode.
        /// </summary>
        public static string Settings_EnableDevMode {
            get {
                return ResourceManager.GetString("Settings_EnableDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Task_Next {
            get {
                return ResourceManager.GetString("Task_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any task planned at the moment..
        /// </summary>
        public static string Task_NoTaskPlanned {
            get {
                return ResourceManager.GetString("Task_NoTaskPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need help?.
        /// </summary>
        public static string TaskOverdue_NeedHelp {
            get {
                return ResourceManager.GetString("TaskOverdue_NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need more time.
        /// </summary>
        public static string TaskOverdue_NeedMoreTime {
            get {
                return ResourceManager.GetString("TaskOverdue_NeedMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time for this task has ran out..
        /// </summary>
        public static string TaskOverdue_TimeRanOut {
            get {
                return ResourceManager.GetString("TaskOverdue_TimeRanOut", resourceCulture);
            }
        }
    }
}
